//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BossEII : Unit, IBoss
	{
        public BossEII(Player p, Case c)
        {
            MovePoints = 2;
            AttackPoints = 4;
            DefensePoints = 2;
            HP = 10;
            Player = p;
            Case = c;
            CreationTime = 5;
            Cost = 200;
        }
	}
}

