//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;

	public class CaseFactory : ICaseFactory
	{

        public CaseFactory()
        {
        }

        public Case makeCase(int type)
        {
            switch (type)
            {
                case 0:
                    return new Mountain();
                case 1:
                    return new Plain();
                case 2:
                    return new Desert();
                default :
                    throw new System.NotImplementedException();
            }
        }
	}
}

