//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;

	public class CaseDecorator : Case, ICaseDecorator
	{
        public virtual ICase Case { get; set; }

        public CaseDecorator(ICase caseToDecorate)
        {
            SqPos = caseToDecorate.SqPos;
            this.Case = caseToDecorate;
        }

        public override int Foods
        {
            get
            {
                return Case.Foods;
            }
            set
            {
                Case.Foods = value;
            }
        }

        public override int Minerals
        {
            get
            {
                return Case.Minerals;
            }
            set
            {
                Case.Minerals = value;
            }
        }

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw)
		{
            Case.afficher(sender, e, fw);
		}

	}
}

