//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;

	public class CaseDecorator : Case, ICaseDecorator
	{
		public virtual Case Case { get;	set; }

		public override void removeUnit(int unit_id)
		{
			throw new System.NotImplementedException();
		}

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw)
		{
			throw new System.NotImplementedException();
		}

	}
}

