//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using System.Drawing;

	public class Fruit : CaseDecorator, IFruit
	{
        public Fruit(ICase caseToDecorate)
        {
            Case = caseToDecorate;
            additional_food = 2;
        }

		public virtual int additional_food { get; set; }

		public virtual void addFood(int additional_food)
		{
			throw new System.NotImplementedException();
		}

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw)
        {
            Case.afficher(sender, e, fw);
            e.Graphics.DrawImage(fw.getBonusImage(0), 50 * sqPos[0], 50 * sqPos[1], 50, 50);
		}

	}
}


