//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameBuilder : IGameBuilder
	{
		public virtual void createMap()
		{
			throw new System.NotImplementedException();
		}

		public virtual void createPlayers()
		{
			throw new System.NotImplementedException();
		}

		public virtual void createGame()
		{
			throw new System.NotImplementedException();
		}

	}
}

