//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class INFOFactory : ICivilizationFactory
	{
		public virtual void addBoss()
		{
			throw new System.NotImplementedException();
		}

		public virtual void addStudent()
		{
			throw new System.NotImplementedException();
		}

		public virtual void addTeacher()
		{
			throw new System.NotImplementedException();
		}

	}
}

