//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using System.Drawing;

    public class Iron : CaseDecorator, IIron
    {
        public Iron(ICase caseToDecorate)
        {
            Case = caseToDecorate;
            this.sqPos = caseToDecorate.sqPos;
            additional_minerals = 2;
        }

        public virtual int additional_minerals { get; set; }

        public virtual void addMinerals(int additional_minerals)
        {
            throw new System.NotImplementedException();
        }

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw)
        {
            Case.afficher(sender, e, fw);
            e.Graphics.DrawImage(fw.getBonusImage(1), 50 * Case.sqPos[0], 50 * Case.sqPos[1], 50, 50);
        }

    }
}

