//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class Map : IMap
    {

        public virtual List<Case> grid { get; set; }
        private MapStrategy mapStrategy { get; set; }

        public Map()
        {
        }

        public void setMapStrategy(MapStrategy mapStrategy)
        {
            this.mapStrategy = mapStrategy;
        }

        public virtual MapType size
        {
            get;
            set;
        }

        public void createMap()
        {
            mapStrategy.createMap(grid);
        }

        public void afficher()
        {
        }
    }
}

