//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Wrapper;

	public class SmallMapStrategy : MapStrategy, ISmallMapStrategy
	{
		unsafe public override void createMap(List<ICase> map)
		{
            WrapperAlgo algo = new WrapperAlgo();
            CaseFactory factory = new CaseFactory();
            int** algoMap = algo.createMap(25, 25);
            for (int j = 0; j < 25; j++)
            {
                for (int i = 0; i < 25; i++)
                {
                    ICase newCase = factory.makeCase(algoMap[i][j]);
                    map.Add(newCase);
                    newCase.sqPos = new int[2] { i, j };
                }
            }
		}

	}
}

