//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Wrapper;

	public class SmallMapStrategy : MapStrategy, ISmallMapStrategy
	{
		unsafe public override void createMap(List<ICase> map)
		{
            WrapperAlgo algo = new WrapperAlgo();
            CaseFactory factory = new CaseFactory();
            int** algoMap = algo.createMap(25, 25);
            int** algoBonusesMap = algo.createBonusesMap(25, 25, 0.1);
            for (int j = 0; j < 25; j++)
            {
                for (int i = 0; i < 25; i++)
                {
                    switch (algoBonusesMap[i][j])
                    {
                        case 1:
                            ICaseDecorator newFruitCase;
                            newFruitCase = new Fruit(factory.makeCase(algoMap[i][j]));
                            newFruitCase.sqPos = new int[2] { i, j };
                            newFruitCase.Case.sqPos = new int[2] { i, j };
                            map.Add(newFruitCase);
                            break;
                        case 2:
                            ICaseDecorator newIronCase;
                            newIronCase = new Iron(factory.makeCase(algoMap[i][j]));
                            newIronCase.sqPos = new int[2] { i, j };
                            newIronCase.Case.sqPos = new int[2] { i, j };
                            map.Add(newIronCase);
                            break;
                        default:
                            ICase newCase;
                            newCase = factory.makeCase(algoMap[i][j]);
                            newCase.sqPos = new int[2] { i, j };
                            map.Add(newCase);
                            break;
                    }
                }
            }
		}
	}
}

