//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class StudentINFO : Unit, IStudent
    {
        public StudentINFO(Player p, Case c)
        {
            movePoints = 2;
            attackPoints = 4;
            defensePoints = 2;
            HP = 10;
        }

        public virtual void attack()
        {
            throw new System.NotImplementedException();
        }
    }
}

