//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.Windows.Forms;
    using System.Drawing;
    using Wrapper;

    public class StudentINFO : Unit, IStudent
    {
        public StudentINFO(IPlayer p, ICase c)
        {
            AttackRange = 1;
            MaxMovePoints = 2;
            MovePoints = 2;
            AttackPoints = 4;
            DefensePoints = 2;
            HP = 10;
            MaxHP = 10;
            Player = p;
            Case = c;
        }

        unsafe public virtual void attack(ICase target)
        {
            WrapperBattleAlgo algo = new WrapperBattleAlgo();
            Dictionary<int, IUnit> EnemyDefPoints = new Dictionary<int, IUnit>();
            foreach(IUnit unit in target.Units)
                EnemyDefPoints.Add((int)((double)unit.DefensePoints / ((double)unit.HP/(double)unit.MaxHP)), unit);
            IUnit targetUnit = EnemyDefPoints[(EnemyDefPoints.Max()).Key];
            int* results = algo.computeBattle(AttackPoints, EnemyDefPoints.Max().Key, HP, targetUnit.HP);
            if (results[0] != 0)
                HP = results[0];
            else
                Case.removeUnit(this);
            if (results[1] != 0)
                targetUnit.HP = results[1];
            else
            {
                target.removeUnit(targetUnit);
                if (MovePoints == 0) MovePoints++;
                move(target);
            }
        }

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw, int x, int y)
        {
            if (Case.Units.OfType<TeacherINFO>().Count() != 0)
            {
                if (Case.Units.OfType<BossINFO>().Count() != 0)
                    e.Graphics.DrawImage(fw.getUnitImage(4, Player.Color), x+2, y+2, 25, 25);
                else
                    e.Graphics.DrawImage(fw.getUnitImage(1, Player.Color), x+2, y+2, 25, 25);

                //Affichage du nombre d'unités du même type
                if (Case.Units.OfType<StudentINFO>().Count() > 1)
                {
                    e.Graphics.DrawString(Case.Units.OfType<StudentINFO>().Count().ToString(), new Font("Arial", 7, FontStyle.Bold), new SolidBrush(Color.Black), x + 16, y + 16);
                    e.Graphics.DrawString(Case.Units.OfType<StudentINFO>().Count().ToString(), new Font("Arial", 6), new SolidBrush(Color.White), x + 16, y + 16);
                }
            }
            else
            {
                if (Case.Units.OfType<BossINFO>().Count() != 0)
                    e.Graphics.DrawImage(fw.getUnitImage(3, Player.Color), x + 6, y + 6, 38, 38);
                else
                    e.Graphics.DrawImage(fw.getUnitImage(2, Player.Color), x + 6, y + 6, 38, 38);

                //Affichage du nombre d'unités du même type
                if (Case.Units.OfType<StudentINFO>().Count() > 1)
                {
                    e.Graphics.DrawString(Case.Units.OfType<StudentINFO>().Count().ToString(), new Font("Arial", 11, FontStyle.Bold), new SolidBrush(Color.Black), x + 28, y + 28);
                    e.Graphics.DrawString(Case.Units.OfType<StudentINFO>().Count().ToString(), new Font("Arial", 10), new SolidBrush(Color.White), x + 28, y + 28);
                }
            }
        }
    }
}

