//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using System.Drawing;

    public class TeacherEII : Unit, ITeacher
    {
        public TeacherEII(IPlayer p, ICase c)
        {
            MovePoints = 2;
            AttackPoints = 0;
            DefensePoints = 2;
            HP = 1;
            Player = p;
            Case = c;
        }

        public virtual void createCity()
        {
            throw new System.NotImplementedException();
        }

        public override void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw, int x, int y)
        {
            e.Graphics.DrawImage(fw.getUnitImage(6, Player.Color), x + 6, y + 6, 38, 38);
        }
    }
}

