//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class TeacherINFO : Unit, ITeacher
    {
        public TeacherINFO(Player p, Case c)
        {
            MovePoints = 3;
            AttackPoints = 0;
            DefensePoints = 1;
            HP = 1;
            Player = p;
            Case = c;
        }

        public virtual void createCity()
        {
            throw new System.NotImplementedException();
        }
    }
}

