//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.Windows.Forms;
    using System.Drawing;

    public class Unit : IUnit
    {

        public virtual IPlayer Player { get; set; }
        public virtual int HP { get; set; }
        public virtual int AttackPoints { get; set; }
        public virtual int DefensePoints { get; set; }
        public virtual ICase Case { get; set; }
        public virtual int MaxMovePoints { get; set; }
        public virtual int MovePoints { get; set; }
        public virtual int Cost { get; set; }
        public virtual int CreationTime { get; set; }
        public virtual int Id { get; set; }

        public virtual void move(ICase destination)
        {
            MovePoints -= Math.Abs(destination.SqPos[0] - Case.SqPos[0]);
            MovePoints -= Math.Abs(destination.SqPos[1] - Case.SqPos[1]);
            Case.Units.Remove(this);
            Case = destination;
            destination.Units.Add(this);
        }

        public virtual void passTurn()
        {
            throw new System.NotImplementedException();
        }

        public virtual void defend()
        {
            throw new System.NotImplementedException();
        }

        public virtual void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw, int x, int y)
        {
            throw new System.NotImplementedException();
        }
    }
}

