//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implementation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    public class Unit : IUnit
    {

        public virtual IPlayer Player { get; set; }
        public virtual int HP { get; set; }
        public virtual int AttackPoints { get; set; }
        public virtual int DefensePoints { get; set; }
        public virtual ICase Case { get; set; }
        public virtual int MovePoints { get; set; }
        public virtual int Cost { get; set; }
        public virtual int CreationTime { get; set; }
        public virtual int Id { get; set; }

        public virtual void move(int x, int y)
        {
            /*
            if (movePoints >= pos_x + pos_y - x - y)
            {
                pos_x = x;
                pos_y = y;
            }
             * */
        }

        public virtual void passTurn()
        {
            throw new System.NotImplementedException();
        }

        public virtual void defend()
        {
            throw new System.NotImplementedException();
        }
    }
}

