//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BossINFO : Unit, Boss
	{
		public override void move()
		{
			throw new System.NotImplementedException();
		}

		public override void passTurn()
		{
			throw new System.NotImplementedException();
		}

	}
}

