//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Case : Case
	{
		private int minerals
		{
			get;
			set;
		}

		private int pos_x
		{
			get;
			set;
		}

		private int pos_y
		{
			get;
			set;
		}

		private int food
		{
			get;
			set;
		}

		private List<Unit> units
		{
			get;
			set;
		}

		public virtual void removeUnit(int unit_id)
		{
			throw new System.NotImplementedException();
		}

		public virtual void afficher(int x, int y)
		{
			throw new System.NotImplementedException();
		}

	}
}

