//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class City : City
	{
		private int population
		{
			get;
			set;
		}

		private int pos_x
		{
			get;
			set;
		}

		private int pos_y
		{
			get;
			set;
		}

		private Player player
		{
			get;
			set;
		}

		private ProductionType current_prod
		{
			get;
			set;
		}

		private int owned_minerals
		{
			get;
			set;
		}

		private int owned_food
		{
			get;
			set;
		}

		public virtual void produceUnits()
		{
			throw new System.NotImplementedException();
		}

		public virtual void changeProduction()
		{
			throw new System.NotImplementedException();
		}

		public virtual void upgradePopulation()
		{
			throw new System.NotImplementedException();
		}

	}
}

