//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Player : Player
	{
		private string pseudo
		{
			get;
			set;
		}

		private CivilizationType civilization
		{
			get;
			set;
		}

		private int score
		{
			get;
			set;
		}

		public virtual void chooseCivilization()
		{
			throw new System.NotImplementedException();
		}

		public virtual void endTurn()
		{
			throw new System.NotImplementedException();
		}

		public virtual void move()
		{
			throw new System.NotImplementedException();
		}

		public virtual void passTurn()
		{
			throw new System.NotImplementedException();
		}

		public virtual void attack()
		{
			throw new System.NotImplementedException();
		}

		public virtual void changeCityProduction()
		{
			throw new System.NotImplementedException();
		}

		public virtual void produceUnits()
		{
			throw new System.NotImplementedException();
		}

	}
}

