//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Unit : Unit
	{
		private int HP
		{
			get;
			set;
		}

		private int attack
		{
			get;
			set;
		}

		private int defense
		{
			get;
			set;
		}

		private int pos_x
		{
			get;
			set;
		}

		private int pos_y
		{
			get;
			set;
		}

		private int move_points
		{
			get;
			set;
		}

		private int cost
		{
			get;
			set;
		}

		private int id
		{
			get;
			set;
		}

		public virtual void move()
		{
			throw new System.NotImplementedException();
		}

		public virtual void passTurn()
		{
			throw new System.NotImplementedException();
		}

	}
}

