//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Map : IMap
	{
		private int height
		{
			get;
			set;
		}

		private int width
		{
			get;
			set;
		}

		private MapType type
		{
			get;
			set;
		}

		private List<Case> cases
		{
			get;
			set;
		}

		private int map_id
		{
			get;
			set;
		}

		public virtual CaseFactory CaseFactory
		{
			get;
			set;
		}

		public virtual IEnumerable<Case> Case
		{
			get;
			set;
		}

	}
}

