//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MapStrategy : IMapStrategy
	{
		public virtual int height
		{
			get;
			set;
		}

		public virtual int width
		{
			get;
			set;
		}

		public virtual void createMap()
		{
			throw new System.NotImplementedException();
		}

	}
}

