//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Implémentation
{
	using Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Unit : IUnit
	{
		public virtual int HP
		{
			get;
			set;
		}

		public virtual int attack
		{
			get;
			set;
		}

		public virtual int defense
		{
			get;
			set;
		}

		public virtual int pos_x
		{
			get;
			set;
		}

		public virtual int pos_y
		{
			get;
			set;
		}

		public virtual int move_points
		{
			get;
			set;
		}

		public virtual int cost
		{
			get;
			set;
		}

		public virtual int id
		{
			get;
			set;
		}

		public virtual int creationTime
		{
			get;
			set;
		}

		public virtual void move()
		{
			throw new System.NotImplementedException();
		}

		public virtual void passTurn()
		{
			throw new System.NotImplementedException();
		}

		public virtual void defend()
		{
			throw new System.NotImplementedException();
		}

        void main()
        {
            Unit Boss = new Unit();
            Boss.attack = 10;
        }

	}
}

