//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;

	/// <remarks>Decorateur</remarks>
	public interface ICaseDecorator  : ICase
	{
        ICase Case { get; set; }

        void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw);
	}
}

