//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using System.Drawing;

	public interface ICase
    {
        int[] sqPos { get; set; }
        int minerals { get; set; }
        int food { get; set; }
        List<IUnit> units { get; set; }
        ICity city { get; set; }
        bool Selected { get; set; }

        void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw);
        void addUnit(IUnit unit);
        void removeUnit(int unit_id);
	}
}

