//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using Implementation;
    using System.Drawing;

	public interface ICase
    {
        int[] sqPos { get; set; }
        int minerals { get; set; }
        int food { get; set; }
        List<Unit> units { get; set; }
        City city { get; set; }

        void afficher(object sender, PaintEventArgs e, CaseImageFlyweight fw);
        void addUnit(Unit unit);
        void removeUnit(int unit_id);
	}
}

