//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.Windows.Forms;

	public interface ICity 
	{
        String Name { get; set; }
        int Population { get; set; }
        ICase Position { get; set; }
        IPlayer Player { get; set; }
        Implementation.ProductionType Current_prod { get; set; }
        int OwnedMinerals { get; set; }
        int OwnedFoods { get; set; }
        int Needed_minerals { get; set; }

        void updateCity(IMap map);

		void produceBoss();

        void produceStudent();

        void produceTeacher();

		void upgradePopulation();

        void spawnUnit(Implementation.ProductionType type);

        void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw, int x, int y);
	}
}

