//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ICity 
	{
		void produceBoss(Implementation.Unit unit);

        void produceStudent();

        void produceTeacher();

		void changeProduction();

		void upgradePopulation();

        void spawnUnit(Implementation.Unit unit);

	}
}

