//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ICity 
	{
        String Name { get; set; }
        int Population { get; set; }
        ICase Position { get; set; }
        IPlayer Player { get; set; }
        Implementation.ProductionType Current_prod { get; set; }
        int Owned_minerals { get; set; }
        int Owned_food { get; set; }

		void produceBoss(IUnit unit);

        void produceStudent();

        void produceTeacher();

		void changeProduction();

		void upgradePopulation();

        void spawnUnit(IUnit unit);

	}
}

