//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGame 
	{
        Queue<IPlayer> Players { get; set; }
        IPlayer Winner { get; set; }
        IPlayer CurrentPlayer { get; set; }
        List<IPlayer> Loosers { get; set; }
        IMap Map { get; set; }
        int Turns { get; set; }

		void addLooser();

		bool isWinner();

        bool isLooser();

        bool isSpectator(IPlayer p);

		void nextPlayer();

	}
}

