//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGame 
	{
        Dictionary<int, IPlayer> Players { get; set; }
        IPlayer Winner { get; set; }
        Dictionary<int, IPlayer> Loosers { get; set; }
        IMap Map { get; set; }

		void addLooser(IPlayer p);

		void endGame();

		void isWinner();

		void isSpectator(IPlayer p);

		void startNewTurn();

	}
}

