//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Monteur</remarks>
	public interface IGameBuilder 
	{

        IMap Map { get; set; }

        void createMap(int players);
        void createPlayers(int players, List<String> names, List<String> civs);
        IGame build();

	}
}

