//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;

	/// <remarks>Poids-Mouche</remarks>
	public interface IMap 
	{
        List<ICase> grid { get; set; }
        IMapStrategy mapStrategy { get; set; }
        ICase SelectedCase { get; set; }
        IUnit SelectedUnit { get; set; }

        void setMapStrategy(IMapStrategy mapStrategy);
        void createMap(Queue<IPlayer> plqu);
        void afficher(object sender, PaintEventArgs e, IPlayer currPlayer);
        void select(int x, int y);
        void moveTo(int x, int y);
        void attack(int x, int y);
        void buildCity(int x, int y, IPlayer currPlayer);
        void reveal(object sender, PaintEventArgs e);
        void drawMoveBorders();
        void drawAttackBorders();
        void circleEnemies(IPlayer currPlayer);
        void drawCityPossibilities(IPlayer currPlayer);
	}
}

