//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Windows.Forms;
    using Implementation;

	/// <remarks>Poids-Mouche</remarks>
	public interface IMap 
	{
        List<Case> grid { get; set; }

        void afficher(PictureBox pb);
	}
}

