//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPlayer 
	{
		void chooseCivilization();

		void endTurn();

		void move();

		void passTurn();

		void attack();

		void changeCityProduction();

		void produceUnits(Implementation.City c, Implementation.Unit u);

	}
}

