//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.Windows.Forms;

	public interface IUnit 
	{
        IPlayer Player { get; set; }
        int HP { get; set; }
        int AttackPoints { get; set; }
        int DefensePoints { get; set; }
        ICase Case { get; set; }
        int MovePoints { get; set; }
        int Cost { get; set; }
        int CreationTime { get; set; }
        int Id { get; set; }


		void move(int x, int y);

		void passTurn();

		void defend();

        void afficher(object sender, PaintEventArgs e, ICaseImageFlyweight fw, int x, int y);
	}
}

